// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkx167vKClrxdzxEzYVv4K4a6UQe0THFE',
    appId: '1:966816861961:android:d5dcc5447f66d2549f4dd8',
    messagingSenderId: '966816861961',
    projectId: 'osclub-orca',
    storageBucket: 'osclub-orca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ48sUJhdhkTbaHbb9r5TvK_SqBrBcXH4',
    appId: '1:966816861961:ios:2a7cae266cf6d2b29f4dd8',
    messagingSenderId: '966816861961',
    projectId: 'osclub-orca',
    storageBucket: 'osclub-orca.firebasestorage.app',
    iosClientId: '966816861961-5dseucupt4mh1ldsvija19g92u8j228n.apps.googleusercontent.com',
    iosBundleId: 'com.example.orca',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2RcXixZJiXRZIJUBXSfb-0OFdNZe4xME',
    appId: '1:966816861961:web:09c079ead61f3b849f4dd8',
    messagingSenderId: '966816861961',
    projectId: 'osclub-orca',
    authDomain: 'osclub-orca.firebaseapp.com',
    storageBucket: 'osclub-orca.firebasestorage.app',
    measurementId: 'G-ENVSKJGXXC',
  );

}